apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dpl
  labels:
    app: my-app
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
        - name: nginx-controller
          image: nginx:1.7.1
  replicas: 4