apiVersion: v1
kind: Pod
metadata:
  name: pod-with-security-context
  namespace: default
  labels:
    app: pod-with-security-context
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx-privileged
      image: nginx
      securityContext:
        runAsUser: 0
    - name: nginx-unprivileged
      image: nginxinc/nginx-unprivileged
      securityContext:
        runAsUser: 1001 #runs as user 1001 instead of 1000
        capabilities:
          add: [ "NET_ADMIN" ]
          drop: [ "ALL" ]